version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: bodegia
      POSTGRES_USER: bodegia
      POSTGRES_PASSWORD: bodegia123 
    ports: 
      - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ../db/init:/docker-entrypoint-initdb.d:ro

  api:
    build:
      context: ../../services/api
    env_file:
      - ../../services/api/.env
    depends_on: 
      - db 
    ports: ["3000:3000"]

  web:
    build:
      context: ../../apps/web
    env_file:
      - ../../apps/web/.env
    depends_on: 
      - api
    ports: ["5173:5173"]

volumes:
  pgdata: